import { calculateDecision } from './decision-engine.js';
import { findInstrument, getProviderStatus, demoCatalog } from './data-provider.js';
import './quote-bridge.js';

const $=s=>document.querySelector(s), main=$('main'), store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const load=k=>JSON.parse(localStorage.getItem(k)||'[]');
const provider=getProviderStatus();
const modeBadge=document.querySelector('.demo');
const setModeLabel=mode=>{if(modeBadge)modeBadge.textContent=mode==='configured'?'● YAPILANDIRILMIŞ EOD MODU':'● DEMO VERİ MODU'};
const status=document.createElement('div');status.className='provider-status';status.textContent=`Veri kaynağı: ${provider.provider} · Son güncelleme: ${provider.lastSuccessfulUpdate} · Gerçek zamanlı: Hayır`;main.prepend(status);
setModeLabel('demo');
fetch('http://127.0.0.1:4180/api/status').then(r=>r.ok?r.json():Promise.reject(new Error('servis yanıtı geçersiz'))).then(s=>{setModeLabel(s.mode);status.textContent=`Python veri servisi: ${s.provider} · Son güncelleme: ${s.lastSuccessfulUpdate} · Gerçek zamanlı: Hayır · ${s.mode==='demo'?'Demo mod':'Yapılandırılmış mod'}`}).catch(()=>{setModeLabel('demo');status.textContent='Python veri servisi bağlı değil · Yerel demo katalog kullanılıyor · Gerçek zamanlı: Hayır'});
const todayLabel=new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date());
const heroDate=document.querySelector('.hero .muted');
if(heroDate)heroDate.textContent=`Piyasa özeti · ${todayLabel}`;
const nav=document.createElement('nav');nav.className='terminal-nav';nav.innerHTML='<a class="active" href="#market">Piyasa</a><a href="#screener">Screener</a><a href="#signals">Sinyaller</a><a href="#news">Haberler</a><a href="#portfolio">Portföy</a><a href="#calendar">Takvim</a><span class="nav-spacer"></span><span class="nav-mode">TR · Demo</span>';document.querySelector('header').append(nav);
const rows=demoCatalog.map((i,n)=>`<div class="table-row"><b>${i.symbol}</b><span>${i.exchange}</span><span>${i.sector}</span><span>${i.currency==='TRY'?'₺':'$'}${i.price.toFixed(2)}</span><span class="${n%3===1?'loss':'gain'}">${n%3===1?'−':'+'}${(n%3===1?1.42:2.18).toFixed(2)}%</span><span class="signal">${i.coverage==='demo'?'İZLE':'KAPSAM DIŞI'}</span></div>`).join('');const market=document.createElement('section');market.className='market-terminal';market.innerHTML=`<div class="terminal-head"><span>PİYASA TERMİNALİ</span><span>Gün sonu · Demo</span></div><div class="breadth"><div><b>1.248</b><span>Yükselen</span></div><div><b>786</b><span>Düşen</span></div><div><b>64</b><span>Yeni zirve</span></div><div><b>31</b><span>Yeni dip</span></div><div><b>%58,4</b><span>SMA50 üzeri</span></div></div><div class="market-table"><div class="table-row table-head"><span>Sembol</span><span>Varlık</span><span>Sektör</span><span>Fiyat</span><span>Değişim</span><span>Sinyal</span></div>${rows}</div>`;main.insertBefore(market,document.querySelector('.hero'));
const suggestions=document.createElement('div');suggestions.id='searchSuggestions';suggestions.className='search-suggestions';document.querySelector('.search').append(suggestions);function drawSuggestions(){const q=$('#symbol').value.trim().toLowerCase();const hits=demoCatalog.filter(i=>!q||`${i.symbol} ${i.name} ${i.sector} ${i.assetType}`.toLowerCase().includes(q)).slice(0,6);suggestions.innerHTML=hits.map(i=>`<button class="suggestion" data-symbol="${i.symbol}"><b>${i.symbol}</b> · ${i.name} · ${i.exchange} · ${i.sector}</button>`).join('')||'<span class="muted">Katalogda eşleşme yok.</span>';suggestions.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{$('#symbol').value=b.dataset.symbol;suggestions.innerHTML='';$('#analyze').click()})}$('#symbol').addEventListener('input',drawSuggestions);drawSuggestions();
const quick=document.createElement('section');quick.className='quick-grid';quick.innerHTML='<article id="signals"><div class="quick-head">EN ÇOK YÜKSELENLER <span>Gün sonu</span></div><div class="quick-row"><b>THYAO</b><span class="gain">+2,18%</span><em>Ulaştırma</em></div><div class="quick-row"><b>BIMAS</b><span class="gain">+2,18%</span><em>Perakende</em></div><div class="quick-row"><b>GARAN</b><span class="gain">+2,18%</span><em>Bankacılık</em></div></article><article id="news"><div class="quick-head">HABER AKIŞI <span>Kaynaklı</span></div><div class="news-row"><b>03 Eki</b><span>KAP ve SEC bağlantıları kaynak kartlarında hazır.</span></div><div class="news-row"><b>03 Eki</b><span>Gerçek veri bağlantısı etkin değil.</span></div></article><article id="calendar"><div class="quick-head">TAKVİM <span>Yaklaşan</span></div><div class="news-row"><b>—</b><span>Takvim sağlayıcı bağlantısı bekliyor.</span></div></article>';main.insertBefore(quick,document.querySelector('.hero'));

function card(title,body){const el=document.createElement('article');el.className='panel';el.innerHTML=`<div class="panel-title"><h3>${title}</h3></div>${body}`;main.insertBefore(el,$('.lower'));return el}
const controls=card('Senaryo ve maliyet girişi','<p class="muted">Demo veriyle yerel hesaplama. Gerçek piyasa verisi değildir.</p><div class="form-grid"><label>Fiyat<input id="fPrice" type="number" value="312.4" step=".01"></label><label>Hedef<input id="fTarget" type="number" value="350" step=".01"></label><label>Alım üst sınırı<input id="fHigh" type="number" value="300" step=".01"></label><label>Alış maliyeti %<input id="fBuy" type="number" value=".15" step=".01"></label><label>Satış maliyeti %<input id="fSell" type="number" value=".15" step=".01"></label></div><button id="recalculate">Kararı yeniden hesapla</button>');
const chart=card('Fiyat seviyeleri','<span class="tag">Demo grafik</span><canvas id="priceChart" height="190" aria-label="Fiyat seviyeleri grafiği"></canvas><table class="level-table"><caption>Grafik seviyeleri</caption><thead><tr><th>Seviye</th><th>Değer</th><th>Anlamı</th></tr></thead><tbody id="levelRows"></tbody></table>');
const alerts=card('Fiyat ve net getiri alarmları','<div class="form-grid"><label>Fiyat alarmı<input id="aPrice" type="number" value="300" step=".01"></label><label>Minimum net getiri %<input id="aNet" type="number" value="5" step=".01"></label></div><button id="saveAlert">Alarmı kaydet</button> <button id="clearAlert" class="secondary">Alarmı sil</button> <button id="notifyPermission" class="secondary">Bildirimleri etkinleştir</button><p id="alertStatus" class="muted"></p>');
function decision(){return calculateDecision({price:+$('#fPrice').value,target:+$('#fTarget').value,buyLow:285,buyHigh:+$('#fHigh').value,buyCost:+$('#fBuy').value,sellCost:+$('#fSell').value,stop:+$('#fPrice').value*.95,thesis:'intact',dataStatus:'demo'});}
function render(){const r=decision();$('#net').textContent=`%${r.net.toFixed(2)}`;$('#gross').textContent=`%${r.gross.toFixed(2)}`;$('#ratio').textContent=r.ratio===null?'—':r.ratio.toFixed(2)+':1';$('#newBuy').textContent=r.newBuy;$('#holding').textContent=r.holding;$('#reason').textContent=r.reason;drawChart();checkAlert(r)}
window.addEventListener('trader:quote-updated',()=>{if($('#fPrice'))render()});window.addEventListener('trader:quote-unavailable',()=>{const s=document.querySelector('.provider-status');if(s)s.textContent='Python veri servisi bağlı değil · Yerel demo katalog kullanılıyor · Gerçek zamanlı: Hayır'});
function drawChart(){const c=$('#priceChart'),ctx=c.getContext('2d'),w=c.clientWidth||700,h=c.height,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);const p=+$('#fPrice').value,t=+$('#fTarget').value,high=+$('#fHigh').value,low=285,stop=p*.95,min=Math.min(low,stop)*.96,max=Math.max(t,p)*1.06,x=v=>24+(v-min)/(max-min)*(w-48);ctx.clearRect(0,0,w,h);ctx.fillStyle='#34a853';ctx.globalAlpha=.12;ctx.fillRect(x(low),30,x(high)-x(low),h-65);ctx.globalAlpha=1;[[low,'#34a853','Alım bandı'],[stop,'#fbbc05','Risk seviyesi'],[p,'#4285f4','Güncel fiyat'],[t,'#ea4335','Baz hedef']].forEach(([v,col,l])=>{const px=x(v);ctx.strokeStyle=col;ctx.lineWidth=v===p?3:2;ctx.beginPath();ctx.moveTo(px,25);ctx.lineTo(px,h-30);ctx.stroke();ctx.fillStyle=col;ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(l,px,16);ctx.fillText(v.toFixed(2),px,h-10)});$('#levelRows').innerHTML=`<tr><td>Alım bandı</td><td>₺${low.toFixed(2)}–₺${high.toFixed(2)}</td><td>Yeni giriş bölgesi</td></tr><tr><td>Güncel fiyat</td><td>₺${p.toFixed(2)}</td><td>Demo gün sonu</td></tr><tr><td>Risk seviyesi</td><td>₺${stop.toFixed(2)}</td><td>Koruma seviyesi</td></tr><tr><td>Baz hedef</td><td>₺${t.toFixed(2)}</td><td>Senaryo hedefi</td></tr>`}
function checkAlert(r){const a=JSON.parse(localStorage.getItem('trader-alert')||'null');if(a)$('#alertStatus').textContent=`Alarm aktif: fiyat ≤ ${a.price} veya net potansiyel ≥ %${a.net}. ${+$('#fPrice').value<=a.price||r.net>=a.net?'Koşul gerçekleşti.':'Henüz tetiklenmedi.'}`}
$('#recalculate').onclick=render;$('#saveAlert').onclick=()=>{store('trader-alert',{price:+$('#aPrice').value,net:+$('#aNet').value});checkAlert(decision())};$('#clearAlert').onclick=()=>{localStorage.removeItem('trader-alert');$('#alertStatus').textContent='Alarm silindi.'};$('#notifyPermission').onclick=async()=>{if('Notification' in window){const p=await Notification.requestPermission();$('#alertStatus').textContent=p==='granted'?'Tarayıcı bildirimleri etkin.':'Bildirim izni verilmedi.'}else $('#alertStatus').textContent='Bu tarayıcı bildirimleri desteklemiyor.'};render();

const positions=card('Portföy pozisyonları','<div id="positions"></div><div class="form-grid"><label>Sembol<input id="pSymbol" value="THYAO"></label><label>Adet<input id="pQty" type="number" value="0" min="0"></label><label>Ortalama maliyet<input id="pCost" type="number" value="0" min="0" step=".01"></label></div><button id="addPosition">Pozisyon ekle</button>');
function drawPositions(){const ps=load('trader-positions');$('#positions').innerHTML=ps.length?ps.map((p,i)=>{const q=findInstrument(p.symbol),price=q?.price??0,cur=q?.currency??'—',pnl=(price-p.cost)*p.qty;return `<div class="watch-line"><span><b>${p.symbol}</b> · ${p.qty} adet · ${cur} ${p.cost}</span><span>${q?`${cur} ${pnl.toFixed(2)} · ${q.name}`:'Fiyat verisi yok'} <button data-remove="${i}" class="secondary">Sil</button></span></div>`}).join(''):'Pozisyon yok.';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=load('trader-positions');a.splice(+b.dataset.remove,1);store('trader-positions',a);drawPositions()})}drawPositions();$('#addPosition').onclick=()=>{const s=$('#pSymbol').value.toUpperCase(),q=findInstrument(s);const a=load('trader-positions');a.push({symbol:s,qty:+$('#pQty').value,cost:+$('#pCost').value,currency:q?.currency??'—'});store('trader-positions',a);drawPositions()};

const sources=card('Kaynaklar','<div id="sourceCards" class="source-grid"></div><p class="muted">Bağlantılar resmî referans amaçlıdır; analiz veri sağlayıcısı henüz bağlı değildir.</p>');function drawSources(){const s=findInstrument($('#symbol').value)||demoCatalog[0];$('#sourceCards').innerHTML=`<a href="${s.source||'https://www.kap.org.tr/'}" target="_blank">${s.exchange==='BIST'?'KAP':'SEC'} · ${s.name}</a><a href="https://www.sec.gov/edgar/search/" target="_blank">SEC EDGAR · ABD bildirimleri</a><a href="${s.source||'https://www.kap.org.tr/'}" target="_blank">Şirket / ihraççı açıklamaları</a>`}drawSources();$('#symbol').addEventListener('change',drawSources);

$('#analyze').onclick=()=>{const s=$('#symbol').value.trim().toUpperCase(),i=findInstrument(s);if(s!=='THYAO'){$('#newBuy').textContent='Veri yetersiz';$('#holding').textContent='Veri yetersiz';$('#net').textContent='—';$('#gross').textContent='—';$('#ratio').textContent='—';$('#reason').textContent=i?`${i.symbol} (${i.assetType}, ${i.exchange}) katalogda tanımlı; veri kapsamı bağlı değil.`:`${s||'Sembol'} katalogda bulunamadı.`}else render()};
const watch=card('Takip listesi','<button id="addWatch" class="secondary">+ THYAO ekle</button><div id="watchItems"></div>');let watched=load('trader-watchlist');function drawWatch(){$('#watchItems').innerHTML=watched.length?watched.map(s=>`<div class="watch-line">${s}<span class="tag">Demo · İzleniyor</span></div>`).join(''):'Henüz takip listesine eklenmedi.'}drawWatch();$('#addWatch').onclick=()=>{if(!watched.includes('THYAO'))watched.push('THYAO');store('trader-watchlist',watched);drawWatch()};
